"""Renders the results section of RESEARCH.md from ml/evaluation/results.json (no hand-typed numbers).

Usage: python -m parkflow_ml.report   (rewrites the "## 11. Results" section of RESEARCH.md)
"""
from __future__ import annotations

import json

import pandas as pd

from .config import EVALUATION_DIR, REPO_ROOT

SUBSETS = [
    ("all", "All test samples"),
    ("post_neighbour_saturation", "After a neighbour's saturation event (research subset)"),
    ("target_approaching_or_saturated", "Target zone approaching or saturated (occupancy ≥ 0.80)"),
]
MODELS = [("none", "persistence", "Persistence (no change)"), ("temporal", "ridge", "Ridge — temporal"), ("spatial_temporal", "ridge", "Ridge — spatial-temporal"),
          ("temporal", "hgb", "**A** HGB — temporal-only"), ("spatial_temporal", "hgb", "**B** HGB — spatial-temporal")]


def pp(x: float) -> str:
    return f"{x * 100:.2f}"


def render(r: dict) -> str:
    m = pd.DataFrame(r["metrics"])
    c = pd.DataFrame(r["comparisons"])
    horizons = sorted(m["horizon_min"].unique())
    ev = r["saturation_events"]
    sp = r["splits"]
    out = [
        "## 11. Results",
        "",
        f"*Generated by `python -m parkflow_ml.report` from `ml/evaluation/results.json` (run {r['generated_at']}). "
        "Errors are in **percentage points of occupancy** (MAE × 100). The test period is 2019-11-01 to 2019-12-31, and the test set was evaluated once.*",
        "",
        f"- Zones in the experiment: {r['zones_in_experiment']}; {r['zones_with_neighbours']} of them have at least one neighbour within {r['config']['neighbour_radius_m']} m.",
        f"- Test samples: {sp['test']['samples']:,}, of which {sp['test']['post_neighbour_saturation_samples']:,} "
        f"({100 * sp['test']['post_neighbour_saturation_samples'] / sp['test']['samples']:.1f}%) follow a neighbour's saturation event.",
        f"- Saturation events in 2019 (all hours, experiment zones): {ev['events']:,} in {ev['zones_with_events']} zones; median duration {ev['median_duration_min']:.0f} min.",
        f"- Hyper-parameters chosen on validation: temporal {r['selection']['temporal']['params']}, spatial-temporal {r['selection']['spatial_temporal']['params']}.",
        "",
    ]
    for subset, title in SUBSETS:
        d = m[m["subset"] == subset]
        out += [f"### {title}", "", "| Model | " + " | ".join(f"MAE {h} min" for h in horizons) + " | " + " | ".join(f"RMSE {h}" for h in horizons) + " | R² 15 min |",
                "|---|" + "---:|" * (2 * len(horizons) + 1)]
        for fs, model, label in MODELS:
            row = d[(d["feature_set"] == fs) & (d["model"] == model)].set_index("horizon_min")
            if row.empty:
                continue
            r2 = row.loc[15, "r2"] if 15 in row.index else None
            out.append(f"| {label} | " + " | ".join(pp(row.loc[h, "mae"]) for h in horizons) + " | " + " | ".join(pp(row.loc[h, "rmse"]) for h in horizons)
                       + f" | {r2:.3f} |")
        out.append(f"\n*n = {int(d['n'].max()):,} samples per horizon (varies slightly with target availability).*\n")

    out += ["### A vs B: does neighbour information help?", "",
            "| Subset | Horizon | MAE A | MAE B | Reduction | 95% CI of MAE(A) − MAE(B), pp |", "|---|---:|---:|---:|---:|---:|"]
    for subset, title in SUBSETS:
        for h in horizons:
            row = c[(c["subset"] == subset) & (c["horizon_min"] == h) & (c["model"] == "hgb")].iloc[0]
            lo, hi = row["bootstrap"]["ci95"]
            out.append(f"| {title.split(' (')[0]} | {h} min | {pp(row['mae_temporal'])} | {pp(row['mae_spatial_temporal'])} | {row['mae_reduction_pct']:.2f}% | [{lo * 100:.3f}, {hi * 100:.3f}] |")
    out.append("")
    return "\n".join(out)


def main() -> None:
    r = json.loads((EVALUATION_DIR / "results.json").read_text(encoding="utf-8"))
    doc = REPO_ROOT / "RESEARCH.md"
    text = doc.read_text(encoding="utf-8")
    start = text.index("## 11. Results")
    end = text.index("### Interpretation", start) if "### Interpretation" in text[start:] else text.index("## 12.", start)
    doc.write_text(text[:start] + render(r) + "\n" + text[end:], encoding="utf-8")
    print("RESEARCH.md section 11 regenerated")


if __name__ == "__main__":
    main()
